<a href="https://colab.research.google.com/github/bobir01/ds_tasks/blob/main/vazifa(2_1_3)_yakuniy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Faqatgina `YOUR CODE HERE` yoki "YOUR ANSWER HERE" deyilgan joyga dasturingizni yoki javobingizni yozing

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
NAME = "Mardonov Bobirjon"
COLLABORATORS = "Mohirdev"

---

---
# Ma'lumotlar tahlili

## 2.1. Numpy kutubxonasi bilan ishlash

## Vazifa-4 

## Yakuniy vazifa

In [2]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): Ma'lumotlarni yuklab olish (2-points).

**Ma'lumotlar :** Ma'lumotlar ikkita faylda joylangan bo'lib, bu fayllar nomlari `gm_2020.npz` va `gm_2021.npz` ko'rinishda, bu fayllar mos ravishda GM Uzbekistan tomonidan 2020 va 2021 yillarning yanvar-iyul oylarida ishlab chiqarilgan avtomobillar modellari va ularning sonlari keltirilgan. `npz` kengaytmasidan ko'rinib turibdiki, xar bir fayl o'z ichiga massivlarni(bizning holatda ikkita massiv, (1) Avtomobil modellari nomi, (2) Ishlab chiqarilgan avtomobillar soni) mujassam etgan. 

Masala sharti shundan iboratki, har bir faylni yuklab ularni ikkita mos massivga ajratuvchi funksiyani tuzing. Tuzilajak funksiyangiz argument sifatida fayl nomini qabul qilishini ta'minlang. 

**Muhim**: Massivlar: `models` va `qnts` nomi ostida saqlangan.

**Yordam :**  `load` metodi yordamida yuklab, so'ngra massiv nomlaridan foydalanib natijani qaytaring. 

**Natija**: Agar funksiyaga `gm_2020.npz` faylini uzatilsa, natija quyidagi ko'rinishda bo'lishi mumkin:

(array(['Labo', 'Damas', ......., 'Gentra'], dtype='<U6'), array([ 4521, 30889, ......,  30368]))



***Ma'lumot manbasi***: *gazeta.uz*

In [3]:
def load_data(file_name):
    """Har bir faylni yuklab ularni ikkita mos massivga ajratuvchi funksiyani tuzish """
    # YOUR CODE HERE
    return np.load(file_name)

    raise NotImplementedError()

Funksiyangizni quyidagi cellda tekshirib oling. (Eslatma: Funksiya turli xil yashirin testlar orqali tekshiriladi, maslahatimiz, aldashga urinmang)

In [4]:
"""Funksiyani tekshirish"""
data1 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2020.npz') # ma'lumotlar (2020)
data2 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2021.npz') # ma'lumotlar (2021)

In [26]:
data1['models']

array(['Labo', 'Damas', 'Spark', 'Nexia', 'Cobalt', 'Gentra'], dtype='<U6')

### Masala(2): Jami ishlab chiqarilgan avtomobillar soni. (2-points)

Yuqorida yaratilingan ma'lumotlarni yuklab ajratib oluvchi funksiyamizdan foydalanib, endilikda ma'lumotlar ustida amallar bajaramiz. 

**Masala :** Ma'lumotlardan foydalanib, 2020 va 2021  yillarda ishlab chiqarilgan jami avtomobillar sonini hisoblaydigan funksiya yarating.

**Natija**: (168..., ...734) ko'rinishida bo'ladi. 
 
Bu yerda 168.... ta avtomabil 2020 yilda ishlab chiqarilgan. 2021 yilda esa ...734 ta avtomabil ishlab chiqarilan. 

In [11]:
def total_qnts():
    """Ma'lumotlardan foydalanib, 2020 va 2021 yillarda ishlab chiqarilgan jami avtomobillar sonini hisoblaydigan 
    funksiya yaratish."""
    data1 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2020.npz') # ma'lumotlar (2020)
    data2 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2021.npz') # ma'lumotlar (2021)
    return [data1['qnts'].sum(),data2['qnts'].sum()]
    """masala sharti biroz noaniq bo'libdi shu yerda nataja list'mi yoki tuple'mi aytib o'tilmagan ekan"""
    raise NotImplementedError()

Funksiyangizni quyidagi cellda tekshirib oling. (Eslatma: Funksiya turli xil yashirin testlar orqali tekshiriladi, maslahatimiz, aldashga urinmang)

In [12]:
"""Funksiyani tekshirish"""
total = total_qnts() # 2020 va 2021 yillardagi jami ishlab chiqarilgan avtomabillar
total

[168712, 124734]

### Masala(3): Ba'zi avtomabillarning ishlab chiqarilish sonlari. (3-points)

> Indented block





**Masala :** Tasavvur qiling, ish beruvchi sizdan faqatgina `Damas`, `Nexia`, `Cobalt`, va `Gentra`rusumli avtomabillarni 2020 va 2021 yillarda qancha ishlab chiqarilganini barcha ma'lumotlardan ajratib berishni so'radi. Siz, shu vazifani bajaradigan funksiyani tuzishingiz kerak. 

 **Yordam**: Boolean indekslash mavzusiga murojat qiling.
 
 
 **Natija**: (array([30889, .....  30368]), array([33682 .....  26266])) ko'rinishida bo'ladi

In [30]:
def sel_models():
    """Faqatgina Damas, Nexia, Cobalt, va Gentra rusumli avtomabillarni 2020 va 2021 yillarda qancha ishlab chiqarilganini 
    barcha ma'lumotlardan ajratib olish"""
    data1 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2020.npz') # ma'lumotlar (2020)
    data2 = load_data('/content/drive/MyDrive/Colab Notebooks/ai.tasks/numpy_last/gm_2021.npz') # ma'lumotlar (2021)
    
    boolData1=np.in1d(data1['models'],['Damas','Nexia','Cobalt', 'Gentra'])

    boolData2=np.in1d(data2['models'],['Damas','Nexia','Cobalt', 'Gentra'])
   
    return [data1['qnts'][boolData1], data2['qnts'][boolData2]]



    raise NotImplementedError()



Funksiyangizni quyidagi cellda tekshirib oling. (Eslatma: Funksiya turli xil yashirin testlar orqali tekshiriladi, maslahatimiz, aldashga urinmang)

In [31]:
"""Funksiyani tekshirish"""
sel_cars = sel_models() # 2020 va 2021 yillardagi ishlab chiqarilgan Damas, Nexia, Cobalt, va Gentra rusumli avtomabillar
sel_cars

[array([30889, 41663, 44901, 30368], dtype=int32),
 array([33682, 14442, 36317, 26266], dtype=int32)]

### Masala(4): Ba'zi avtomabillarning ishlab chiqarilish sonlari umumiy ishlab chiqarilgan avtomabilarning qancha foizini tashkil etadi. (3-points)


Yuqorida faqatgina `Damas`, `Nexia`, `Cobalt`, va `Gentra`rusumli avtomabillarni 2020 va 2021 yillarda qancha ishlab chiqarilganini barcha ma'lumotlardan ajratib oldik. 


**Masala :** Ana endilikda shu avtomabillarni jami ishlab chiqarilgan avtomabillarning qancha foizini tashkil etishini hisoblab ko'ramiz. Shu vazifani bajaruvchi funksiyani tuzing. 

 **Yordam**: Masala(2)da jami avtomabillarning sonini hisoblab chiqgan edik, Masala(3)da esa ba'zi avtomabillarning sonini hisoblab topdik. Shu ma'lumotlardan foydalaning. 
 
 **Hisoblash formulasi:** $$\frac{Avtomabil\;soni}{Jami\; avtomabillar\; soni}*100% $$
 
 
 **Natija**: (array([18.30871544, ..... 17.99990516]),
 array([27.00306252, ..... 21.0576106 ])) ko'rinishida bo'ladi
 
 Ya'ni, `Damas` rusumli avtomabil 2020 yilda jami ishlab chiqarishning 18.3% ni tashkil etadi 2021 yilda esa 27% ni tashkil etmoqda va h.k.
 

In [34]:
def ratio_sel_models():
    """Ba'zi avtomabillarning ishlab chiqarish hajmi, jami ishlab chiqarilgan avtomabillar hajmining qanday 
    foizini egallashini hisoblash funksiyasi"""
    return [(sel_cars[0]/total[0])*100, (sel_cars[1]/total[1])*100]
    raise NotImplementedError()

:Funksiyangizni quyidagi cellda tekshirib oling. (Eslatma: Funksiya turli xil yashirin testlar orqali tekshiriladi, maslahatimiz, aldashga urinmang)

In [35]:
"""Funksiyani tekshirish"""
ratio_sel_cars = ratio_sel_models() # 2020 va 2021 yillardagi ishlab chiqarilgan ba'zi avtomabillarning foizdagi ulushi
ratio_sel_cars

[array([18.30871544, 24.69474608, 26.61399308, 17.99990516]),
 array([27.00306252, 11.57823849, 29.11555791, 21.0576106 ])]